### ISSUE TITLE
Invalid many-to-many relationship configuration

### ISSUE THREAD

**Issue by MikhailSiarko** [MaximOvodok/NetCoreNotesApp#2]
Unable to start the project because of wrong many-to-many relationship configuration.

![Annotation 2019-05-20 163500](https://user-images.githubusercontent.com/24798424/73263057-be55df80-41e0-11ea-885e-f4fad1a840ed.jpg)

EF Core can't work with many-to-many relationship without intermediate entity.

**Comment by MaximOvodok** [comment]
Fixed
